### PR TITLE
Sandbox domain configuration for app cryptpad

### PR DESCRIPTION
**Pull request by Ddataa**
## Problem

- no sandbox domain

## Solution

- implement sandbox domain

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Ddataa** [comment]
!gogogadgetoci

**Comment by ericgaspar** [comment]
!testme

**Comment by Ddataa** [comment]
!gogogadgetoci

**Comment by Ddataa** [comment]
here this one @ericgaspar

**Comment by Ddataa** [comment]
!gogogadgetoci

**Comment by Ddataa** [comment]
please !testme

**Comment by tituspijean** [comment]
!testme

**Comment by Ddataa** [comment]
!testme

**Comment by Ddataa** [comment]
please !testme

**Comment by Ddataa** [comment]
superpowa !gogogadgetoci

**Comment by Ddataa** [comment]
please !testme

**Comment by Ddataa** [comment]
please !testme encore

**Comment by Ddataa** [comment]
!testme :1234:

**Comment by Ddataa** [comment]
!testme :carousel_horse

**Comment by Ddataa** [comment]
!testme

**Comment by Ddataa** [comment]
!testme

**Pull request closed without merging**
